definitions:
  api.Metric:
    properties:
      param_one:
        type: string
      param_three:
        type: string
      param_two:
        type: string
    type: object
  api.PingResponse:
    properties:
      message:
        type: string
      search:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: sso
  version: 0.0.1
paths:
  /api/system.metrics/log:
    post:
      parameters:
      - description: Metrics
        in: body
        name: metrics
        required: true
        schema:
          items:
            $ref: '#/definitions/api.Metric'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: not ok
          schema:
            $ref: '#/definitions/api.PingResponse'
        "406":
          description: not ok
          schema:
            type: string
      summary: Check system health
      tags:
      - system
  /api/system.ping:
    get:
      parameters:
      - description: Search query
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: not ok
          schema:
            $ref: '#/definitions/api.PingResponse'
        "406":
          description: not ok
          schema:
            type: string
      summary: Check system health
      tags:
      - system
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
