components:
  schemas:
    api.Metric:
      properties:
        param_one:
          type: string
        param_three:
          type: string
        param_two:
          type: string
      type: object
    api.PingResponse:
      properties:
        message:
          type: string
        search:
          type: string
      type: object
  securitySchemes:
    basic:
      scheme: basic
      type: http
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: sso
  version: 0.0.1
openapi: 3.1.0
paths:
  /api/system.metrics/log:
    post:
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/api.Metric'
              type: array
        description: Metrics
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.PingResponse'
          description: not ok
        "406":
          content:
            application/json:
              schema:
                type: string
          description: not ok
      summary: Check system health
      tags:
      - system
  /api/system.ping:
    get:
      parameters:
      - description: Search query
        in: query
        name: q
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.PingResponse'
          description: not ok
        "406":
          content:
            application/json:
              schema:
                type: string
          description: not ok
      summary: Check system health
      tags:
      - system
servers:
- url: http://localhost:8080
