version: "3"

env:
  SDK_DIR: '{{.TASKFILE_DIR}}'

tasks:
    
  go-generate-grpc-api:
    desc: Generate golang gRPC client/server from proto files
    aliases: [go-gen-grpc]
    dotenv: ['.env']
    silent: true
    cmd: sh $SDK_DIR/scripts/generate.go.sh $GEN_DIR/grpc $SDK_DIR/protos

  go-generate-rest-api:
    desc: Generate golang REST client from swagger docs
    aliases: [go-gen-rest]
    dotenv: ['.env']
    vars:
      CLIENT_DIR: $GEN_DIR/rest
    cmd: swagger generate client -f $SDK_DIR/docs/swagger.yaml -c {{.CLIENT_DIR}}/client -m {{.CLIENT_DIR}}/models