basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: sso
  version: 0.0.1
paths:
  /api/ping:
    get:
      produces:
      - text/html
      responses:
        "200":
          description: ok
          schema:
            type: string
        "406":
          description: not ok
          schema:
            type: string
      summary: Регистрация пользователя
      tags:
      - system
  /register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Registers a new user with the provided nickname, email, and password
      parameters:
      - description: User's nickname
        in: formData
        name: nickname
        required: true
        type: string
      - description: User's email
        in: formData
        name: email
        required: true
        type: string
      - description: User's password
        in: formData
        name: pswd
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Hello BITCH!
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "406":
          description: Not Acceptable
          schema:
            type: string
        "417":
          description: Expectation Failed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Register a new user
      tags:
      - authentication
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
